language: python
matrix:
  include:
    - { python: "2.7" }
    - { python: "3.4" }
    - { python: "3.5" }
    - { python: "3.6" }
    - { python: "3.7", dist: xenial }  # Python 3.7+ requires Xenial
    - { python: "3.8-dev", dist: xenial }  # Python 3.8+ requires Xenial
    - { python: "pypy" }
    - { python: "pypy3" }

install:
  - "pip install --upgrade pip"
  - "pip install --upgrade setuptools"
  - "travis_retry pip install git+git://github.com/TurboGears/crank.git"
  - "travis_retry pip install git+git://github.com/TurboGears/backlash.git"
  - "travis_retry pip install git+git://github.com/TurboGears/Ming.git"
  - "pip install repoze.who"
  - "pip install coverage==4.2"
  - "pip install nose"
  - "pip install --no-binary :all: -e .[testing]"

  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install git+git://github.com/TurboGears/tgext.chameleon_genshi.git; fi 
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install coveralls && export HAS_COVERALLS=1; fi

script: "nosetests -v --with-coverage --cover-package=tg --cover-erase"

after_success:
  - if [[ $HAS_COVERALLS ]]; then coveralls; fi
